### ISSUE TITLE
Pro-tip less with core.pager configuration results in "Pattern not found (press RETURN)" for other commands

### ISSUE THREAD

**Issue by rocketraman** [so-fancy/diff-so-fancy#173]
When using the `core.pager` configuration as specified in the README with the "Pro-tip" of pre-seeding a search pattern with less, other commands such as `git log` show:

`Pattern not found  (press RETURN)`

Once enter is hit, the normal log output is shown. The documentation should probably suggest a better way of doing this, or not suggest it at all.

**Comment by OJFord** [comment]
> The documentation should probably suggest a better way of doing this, or not suggest it at all.

Agreed. Have you found such a way, or are you just putting up with it/not using it?

From an - admittedly cursory - perusal of the man page, I don't think `less` has a way to 'ignore' no-matches.

However, what we can do is set a different pager:
```config
[core]
    pager = less --tabs=4 -RFX
[pager]
    diff = diff-so-fancy | less --tabs=4 -RFX --pattern'^(added|deleted|modified): '
```

To be honest, that's probably a good idea even if you don't want the search pattern, since there's no point running the logs through d-s-f: it'll either do nothing, or present a bug.

**Comment by rocketraman** [comment]
> Agreed. Have you found such a way, or are you just putting up with it/not using it?

No, I just removed the pattern match.

> However, what we can do is set a different pager:

Great -- the `pager.diff` setting works perfectly for `git diff`. Adding this takes care of `show` as well:

```
[pager]
    show = diff-so-fancy | less --tabs=4 -RFX --pattern '^(added|deleted|modified): '
```

> [core]
>     pager = less --tabs=4 -RFX

Using the default `core.pager` seems to be sufficient, so probably no need to document this.

**Comment by rocketraman** [comment]
Another workaround: instead of calling less directly, call a wrapper function or script that checks for the existence of the pattern match or not, and only add `--pattern` if yes. Not too elegant though.

**Comment by OJFord** [comment]
Yep, I did think about that briefly, but that sounds like it could be pretty slow on large files - especially since, unless really clever, it's going to pattern match _twice_ if it does exist. Whereas this should actually be a slight speed-up.

I'll open a PR later to change the recommendation in the docs to be for `pager.diff` only to avoid the no-match issue.

**Comment by paulirish** [comment]
> I'll open a PR later to change the recommendation in the docs to be for pager.diff only to avoid the no-match issue.

SGTM.

**Comment by OJFord** [comment]
Sorry, completely forgot about this! PR open now.
