### ISSUE TITLE
Problem with UTF-8 encoded characters

### ISSUE THREAD

**Issue by britter** [so-fancy/diff-so-fancy#203]
When running a `git show` on apache/commons-lang@86a5960 I get the following error message:

```
"\x{00e8}" does not map to utf8 at /usr/local/Cellar/diff-so-fancy/0.11.1/libexec/lib/node_modules/diff-so-fancy/libexec/diff-so-fancy.pl line 107, <> line 28.
```

Reproduction (with diff-so-fancy set up for git diff):

```
git clone https://github.com/apache/commons-lang.git
cd commons-lang
git show 86a5960
```

**Comment by scottchiefbaker** [comment]
Are you on the latest version. I'm pretty sure we worked around this using:

```
# Set the input (STDIN) as UTF8, but don't give warnings about unknown chars
use open qw(:std :utf8); # http://stackoverflow.com/a/519359
no warnings 'utf8';
```

d-s-f has to assume UTF8 input because there are multiple files of different encodings possible, so these errors can occur on some LATIN text that doesn't map directly to UTF8.

**Comment by britter** [comment]
@scottchiefbaker the problem still exists with version 0.11.4. The commit causing the problem is apache/commons-lang@86a5960. Maybe the problem is caused because our files were broken before and we fixed them in said commit?

**Comment by scottchiefbaker** [comment]
That's entirely possible. Can you recreate the bug with a new commit using the same character?

Honestly though this is just a warning. Perl is telling you it came across a character it couldn't map to a Unicode code point. Sometimes this happens when you mix latin1 and utf8 input files. 

Unless you feel it's part of a larger bug I'm gonna have to chock this up to "the way it is".

**Comment by britter** [comment]
Yes it's probably caused by the fact that the file was broken before and was fixed in that commit.

**Comment by Peter200lx** [comment]
This is an annoying problem though because it messes up the pager. I'm guessing the error is printed to std-out? If I page down below the error and then back up I don't see it re-appear. However if I just scroll down a couple of lines and then back up the pager no-longer matches what was originally printed.

**Comment by OJFord** [comment]
@scottchiefbaker Could dsf just disable Perl warnings completely: `no
warnings;`?

If they appear in the pager like that... I think I'd prefer not to know!

**Comment by scottchiefbaker** [comment]
@OJFord disabling warnings is considered bad practice in 2017. It can expose a lot of errors that might otherwise be missed. If we can I'd like to fix this, but the bug as I see it is unfixable. 

If you have a diff with two different files, one with latin-1 encoding, and the other with UTF-8. Because d-s-f just reads the STDIN from `git-diff` it has no way to know what the incoming encoding is, so we assume everything is UTF-8. This works 99% of the time, except when you mix encodings, and use an encoding that doesn't map cleanly in to UTF-8 (ASCII 127 - 255). This is unfixable in my opinion, and also an **extremely** corner case. It's very uncommon you have this mix of files in the same diff.

Now if there is ANOTHER way to trigger this bug I'm all ears. I don't like this "feature" any more than you guys do, so I'm open to suggestions. If you're able to produce something reproducible I'd be eager to take a look at it again.

**Comment by scottchiefbaker** [comment]
I'm re-opening this issue for now, as I might have a work-around. If you comment out the line in diff-so-fancy that says `binmode STDOUT,':encoding(UTF-8)';` can you tell me if it fixes the extraneous warnings. 

I think if we leave the STDIN -> UTF8 mapping in place, but don't force UTF8 on the output it might solve this issue. The tests all still pass, so I don't THINK it breaks anything.

**Comment by Peter200lx** [comment]
For me the issue was when doing a `git log -p` where files that weren't UTF8 mixed with commit messages that are (at least this is my current theory). Most source files show as `us-ascii` but a couple as `utf-8`, one as `utf-16le`, and strangest one as `unknown-8bit` (`mousepad`/`gedit` complains about that file as well, although `vim` reads it fine)
```
$ diff /usr/share/diff-so-fancy/diff-so-fancy.pl /usr/share/diff-so-fancy/diff-so-fancy.pl.bak
12c12
< #binmode STDOUT,':encoding(UTF-8)';
---
> binmode STDOUT,':encoding(UTF-8)';
```
This does fix the warnings for me, I don't see any encoding errors printed, nor do I see any corrupt characters in my output so far. If this doesn't break anything it seems like a good solution to me.

**Comment by Peter200lx** [comment]
Yup, the `unknown-8bit` file was at least one issue, note the `does not map to utf8` line below the filename. (It was apparently a windows em dash `—` vs `-` )
```
commit d5392595d5b99d0d8033207e88d15dcd33d77e47
Author: Peter Olson <redacted>
Date:   Wed Apr 26 09:09:55 2017 -0700

    Fix non-ascii character (emdash vs -) in noise.cpp

───────────────────────────────────────────────────────────────────────
modified: noise.cpp
"\x{0096}" does not map to utf8, <> line 19.
───────────────────────────────────────────────────────────────────────
@ noise.cpp:48 @ static float redacted(float y0, float y1, float y2, float y3, 
#else

  //lerp2
  //return n1 + (n2 \x96 n1) * delta;^M
  //return n1 + (n2 - n1) * delta;^M

static float redacted (float y0, float y1, float y2, float y3, bool left)
{
```
and after the fix:
```
commit d5392595d5b99d0d8033207e88d15dcd33d77e47
Author: Peter Olson <redacted>
Date:   Wed Apr 26 09:09:55 2017 -0700

    Fix non-ascii character (emdash vs -) in noise.cpp

───────────────────────────────────────────────────────────────────────
modified: noise.cpp
───────────────────────────────────────────────────────────────────────
@ noise.cpp:48 @ static float redacted(float y0, float y1, float y2, float y3,
#else

  //lerp2
  //return n1 + (n2 <96> n1) * delta;^M
  //return n1 + (n2 - n1) * delta;^M

static float redacted(float y0, float y1, float y2, float y3, bool left)
{
```
Also if I make the terminal small enough (15 lines or so) that I have to scroll in that output, the first one is offset a line because of the utf8 error line, while the second one scrolls correctly.

**Comment by OJFord** [comment]
> disabling warnings is considered bad practice in 2017

Even in 'production'?

I agree that anyone should be aiming for no warnings (and obviously no
errors) in any language, but I'd have thought it would be perfectly
reasonable to disable warnings in dsf _releases_, seeing as per above they
render an horrible UX. First response to a non-obvious issue could be
'please try again with warnings enabled like so'.

**Comment by Peter200lx** [comment]
> Even in 'production'?
Disabling all warnings in desktop programms is generally considered bad, but targeted disabling of specific error types that are understood is usually more acceptable I've found. However hopefully we've found a fix here that doesn't require tampering with error returns at all. (Also depends on if `production` is a website or output on someone's own computer. There you have two different issues because one could be exposing internal information to malicious actors and the other is just letting the user know of a problem)

**Comment by rocketraman** [comment]
Just got bit by this with version 1.0.0. A diff in a project of mine contains a corrected file encoding: a special character encoded with ISO-8859-1 in one version, and UTF-8 in a corrected version. When using diff-so-fancy to display this diff, it stops at the line with the char in the different encoding. When running it stand-alone, I see this error message:

```
utf8 "\xA9" does not map to Unicode at /home/raman/.npm-packages/lib/node_modules/diff-so-fancy/lib/diff-so-fancy.pl line 33, <> line 22.
```

However, the *really* annoying bit is that when I run this from `git diff`, **I never see the error message at all**, presumably because git diff pipes through a pager which ignores standard output. This means that, as far as I can tell, I am seeing the complete diff but in fact I am not. This sucks, to say the least (I just got bit by this on a project comparing two branches that should have been substantially the same, and based on diff-so-fancy crapping out on a bad char, they appeared to be, but in reality they were not).

**Comment by rocketraman** [comment]
BTW, I disagree that this is a corner case. Any time you have a file that is incorrectly encoded in something other than UTF-8, and then change it's encoding to UTF-8, you'll trigger this error (and this is NOT uncommon).

Other tools deal with this by showing a hex char or a ? symbol. For example, raw git diff shows this when correcting the encoding of a copyright symbol:

```
-//     Copyright � Me 2017.
+//     Copyright © Me 2017.
```

and less shows:

```
-//     Copyright <A9> Me 2017.
+//     Copyright © Me 2017.
```

Either of the approaches above would be acceptable for diff-so-fancy also.

**Comment by rocketraman** [comment]
In the meantime, I've changed my git `pager.diff` setting to combine stderr with stdout, so at least I see the error message:

```
[pager]
  diff = diff-so-fancy 2>&1 | less --tabs=2 -RFX --pattern '^(added|deleted|modified): '
```

**Comment by scottchiefbaker** [comment]
The problem is that d-s-f reads STDIN coming in from Git. We have no way to know what the encoding is, and in your case it's TWO different encoding schemes (ISO-8859-1 and UTF-8) all coming on the same STDIN. There is no clean way to fix this because the various encoding types from diffs is not consistent ever.

One diff can have multiple files, all with **different** encodings. I like your documentation fix adding `2>&1` I think I'll include that in our docs.

To clarify, this is only an issue when migrating from an encoding scheme that doesn't map directly to UTF-8. 99% of them map fine, it's just the extended characters in ISO-8859 and a couple others that cause problems. I'm open to suggestions though, as I don't have an easy way to solve this.

**Comment by rocketraman** [comment]
> There is no clean way to fix this because the various encoding types from diffs is not consistent ever.

I realize the problem. I'm not asking for a "fix" as such. I'm just asking for bytes that are not valid UTF-8 to be displayed using � or a hex code like `<A9>` in the diff, rather than causing the diff to crap out in the middle. This is exactly what other tools do, like raw `git diff` or `less` for example.

NOTE that the issue about not knowing the encoding is not specific to standard input. Even if you had a reference to a file, it does not contain any meta-data about the encoding of its contents. So there is nothing particular to diff-so-fancy here that other tools don't also have to deal with. Most tools try to detect the encoding and use that, but IMO diff-so-fancy doesn't even have to go that far.

**Comment by rocketraman** [comment]
For example, here is a diff with raw git:

![image](https://user-images.githubusercontent.com/53049/28028226-deb59f28-6569-11e7-87f2-6e18246a2405.png)

Here is the same diff piped through `less`:

![image](https://user-images.githubusercontent.com/53049/28028253-ef4068d2-6569-11e7-9c00-a2457f565713.png)

And finally `diff-so-fancy`:

![image](https://user-images.githubusercontent.com/53049/28028262-f8ae670c-6569-11e7-957b-6506d8eef493.png)

**Comment by rocketraman** [comment]
Simple repro repository:

https://github.com/rocketraman/diff-so-fancy-203-demo

Even github knows how to do this:

https://github.com/rocketraman/diff-so-fancy-203-demo/commit/6e43a854b292872b7c19896418540de60668ba79

**Comment by scottchiefbaker** [comment]
@rocketraman I've spent a ton of time on this issue... it's really hard to deal with multiple inputs while keeping everyone happy with the output. Can you try the `next` branch and see if it addresses this for you? It _appears_ to address the original common-lang issue.

**Comment by rocketraman** [comment]
@scottchiefbaker `next` does indeed solve the problem, thanks! It now shows the invalid char as `\xA9` which is great. I guess more was changed than just commenting out the one line of code mentioned in this ticket above...

**Comment by scottchiefbaker** [comment]
@rocketraman This is a moving target... can you `git pull` and try again. I updated something which should clear up some of those errors even more.

P.S. Text encodings are huge pain in the butt. I'm gonna need a therapist when this is all done :)

**Comment by rocketraman** [comment]
@scottchiefbaker Even better! Now the diff shows the little question-mark-thingy-symbol), and also there is no error message sent to standard err. Great.

And yes, they are. :-)

**Comment by scottchiefbaker** [comment]
I'm gonna mark this as closed then. I don't think my brain can take any more encodings anyway.
