### ISSUE TITLE
"Warning: This appears to be the first time you've run diff-so-fancy" displayed every incocation

### ISSUE THREAD

**Issue by SimenB** [so-fancy/diff-so-fancy#244]
Using the freshly minted 1.1.0 on mac.

![image](https://user-images.githubusercontent.com/1404810/28237432-ce135ff0-693f-11e7-8649-b55e7931fd69.png)

Git config: https://github.com/SimenB/vcsh_git/blob/2f94f33d90261c4690c557bbecc9901d1b00edb3/.gitconfig

**Comment by SimenB** [comment]
This goes away of adding any `[color "diff-highlight"]`. Which is pretty weird!

**Comment by scottchiefbaker** [comment]
Ah... you hit a weird corner case. You already have a d-s-f alias, and you don't have an DiffHighlight colors set. You can also just run d-s-f standalone once (not via your git alias) and it will give you this error with a prompt to set default colors, and you can select N.

The issue is that I can't prompt the user to set colors (or set first-run to false) in less, so the only thing I can do is show the warning. I'm not sure what the best "fix" here is. I could modify the usage to explain how to get rid of that error I suppose?

**Comment by SimenB** [comment]
That worked, thanks!

https://github.com/SimenB/vcsh_git/commit/cba98c2d986c8bea16593fe0d2462708cb993aef

And yes, a better message would be nice 🙂

**Comment by scottchiefbaker** [comment]
@SimenB I'd love a Pull Request on this if you want to try and change the usage for this.

**Comment by SimenB** [comment]
>@SimenB) I'd love a Pull Request on this if you want to try and change the usage for this.

Sure, #250 is a first try.
