### ISSUE TITLE
"Possible typo" when $file_1 or $file_2 eq /dev/null

### ISSUE THREAD

**Issue by tkphd** [so-fancy/diff-so-fancy#333]
Using `diff-so-fancy` 20b70f1 as my `git difftool`, I encounter the following warnings when diffing a file against previous versions:
```bash
$ git diff HEAD~1
Name "DiffHighlight::NEW_HIGHLIGHT" used only once: possible typo at diff-so-fancy line 592.
Name "DiffHighlight::OLD_HIGHLIGHT" used only once: possible typo at diff-so-fancy line 596.
```
The offending lines in `diff-so-fancy` are
```perl
# If the first is /dev/null it's a new file
} elsif ($file_1 eq "/dev/null") {
    my $add_color = $DiffHighlight::NEW_HIGHLIGHT[1];
    return "added: $add_color$file_2$reset_color";
# If the second is /dev/null it's a deletion
} elsif ($file_2 eq "/dev/null") {
    my $del_color = $DiffHighlight::OLD_HIGHLIGHT[1];
    return "deleted: $del_color$file_1$reset_color";
```
The diff of the file *is* displayed, but the constant warnings get annoying.

**Comment by scottchiefbaker** [comment]
What OS and what version of Perl? That's a really weird place to be getting that error.

How do you have `git diff` configured to call d-s-f?

**Comment by tkphd** [comment]
- Debian v9.9 "stretch"
- Perl v5.24.1
- `core.pager=diff-so-fancy | less --tabs=4 -RFX`

**Comment by scottchiefbaker** [comment]
This is version 1.2.5 of d-s-f? How did you install it? 

`$DiffHighlight::NEW_HIGHLIGHT[1]` is a reference to a variable in `DiffHighlight` which is an included library. My guess is that it's not seeing `DiffHighlight` correctly.

**Comment by tkphd** [comment]
Ack, you're right: I copied the cloned d-s-f to another folder, but did not copy the updated lib/. Thanks for the help!

**Comment by scottchiefbaker** [comment]
OK phew. I was getting worried, that was definitely a weird error.

**Comment by bruce-ricard** [comment]
I encountered the same issue. Followed the instructions from the README:

> Installation is as simple as downloading the diff-so-fancy script to a directory in your path.

by copying `diff-so-fancy` to `/usr/local/bin`.
But when I ran it I got similar errors:
```
diff-so-fancy --version
```
> Name "DiffHighlight::NEW_HIGHLIGHT" used only once: possible typo at /usr/local/bin/diff-so-fancy line 592.
Name "DiffHighlight::OLD_HIGHLIGHT" used only once: possible typo at /usr/local/bin/diff-so-fancy line 596.
Diff-so-fancy: https://github.com/so-fancy/diff-so-fancy
Version      : 1.2.6

After finding this issue I also copied the library to `/usr/local/bin/lib`, and it started working.

IMHO this should be explained in the README. Also, IMHO the script should instantly fail when it fails to find the library instead of displaying these outputs.

**Comment by OJFord** [comment]
`diff-highlight` is distributed with `git` (in `contrib`), since it's a Perl script/module it doesn't require any compilation to use, so I think the readme assumes that with the implicit `git` dependency in place, nothing further is needed.

What platform are you on / package manager are you using that installing `git` is not sufficient for its `contrib` dir ending up in a reasonable place?

(I agree the error could be better. I don't know Perl, but `use DiffHighlight;` is  right up near the top, I'm surprised it doesn't error there.)

**Comment by scottchiefbaker** [comment]
@bruce-ricard the documentation you reference is a **link** to a build of the d-s-f script with the included libraries built in. You can:

1. Use the script at the link with no library requirements
2. Use the script in the core of the repo which requires the `diff-highlight` library.
