### ISSUE TITLE
Complete support for git log --graph

### ISSUE THREAD

**Issue by phil-blain** [so-fancy/diff-so-fancy#352]
Currently d-s-f doesn't work correctly with `git log --graph`. Among other things, the headers are not formatted correctly, and the setting to ignore the leading `+/-` is not respected. Example:
~~~
git log --decorate --oneline  -1 --stat -p  git.c
~~~

![no-graph](https://user-images.githubusercontent.com/44212482/67510672-5d5bc000-f663-11e9-8f8a-eb3821bb9bb7.png)

~~~
git log --decorate --oneline --graph -1 --stat -p  git.c
~~~

![graph](https://user-images.githubusercontent.com/44212482/67510731-80866f80-f663-11e9-9fdb-c8434a26d7fb.png)

I guess that is because of the characters `* | / \`  used to display the graph...

That would be a great addition!

**Comment by scottchiefbaker** [comment]
I didn't even know that `git log` showed the actual diffs until this. I like this idea in theory, but the logic to leave the starting `| \ /` and remove the `- +` would be pretty complex. Especially considering this is more of a "corner case" as far as use cases go.

I'll leave this bug open for future conversation. If this were an easy fix I would implement it right away. Because it's not I will leave it open and ponder a solution.

**Comment by OJFord** [comment]
d-s-f works fine with `git log --patch` (`-p`), if enabled in `core.pager`, since it's only the `--graph` flag that introduces the `|` line.

@phil-blain Do you actually use the two together, ordinarily? `--graph` to me seems much less useful when each log entry is large, as it is if `--patch`es are included.

**Comment by phil-blain** [comment]
@OJFord you are right, in fact I had configured a `logo` git alias for `git log --oneline --graph --decorate` and using this alias with `-p` would create the output above. But since then I removed the `--graph` argument from my alias to overcome this limitation in d-s-f.

**Comment by scottchiefbaker** [comment]
Due to the semi-random line indicators that `git graph --log` adds this is not something we can really fix. I've been thinking about it for a while and there is no easy way to do this.

d-s-f is not compatible with `--log`
