### ISSUE TITLE
Enconding problems with color.diff.meta

### ISSUE THREAD

**Issue by firesoft-de** [so-fancy/diff-so-fancy#361]
Hi,
I encountered some problems using diff-so-fancy on windows with
```
git config --global color.diff.meta       "11"
```

Using this option the console produces the following output
```
ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
modified: xxx/xxx/xxx.sh
ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ
@@ -1,8 +1,12 @@
 #!/bin/sh
```
instead of

```
───────────────────────────────────────────────────────────────────────────────
modified: xxx/xxx/xxx.sh
───────────────────────────────────────────────────────────────────────────────
@ xxx/xxx/xxx.sh:4 @
#!/bin/sh
```

**Comment by scottchiefbaker** [comment]
What terminal are you using? The dash character it draws is a unicode character which may cause problems with some terminals. You can see it in action [here](https://github.com/so-fancy/diff-so-fancy/blob/master/diff-so-fancy#L572).

**Comment by firesoft-de** [comment]
I'm using MIGW64 so underneath it should be the default Windows Terminal.

**Comment by scottchiefbaker** [comment]
There is also this [config option](https://github.com/so-fancy/diff-so-fancy#useunicoderuler).

**Comment by firesoft-de** [comment]
I got it running for me (with the unicode symbol) by removing the meta option. I didn't tested if a color value given to meta produces valid output.

Just for the record: With .meta = 11 every mingw window and also every other instance of cmd or powershell shows broken glyphs. Even when git isn't running. Very strange o.O

-------- Ursprüngliche Nachricht --------
Von: Scott Baker <notifications@github.com>
Datum: 01.02.20 19:15 (GMT+01:00)
An: so-fancy/diff-so-fancy <diff-so-fancy@noreply.github.com>
Cc: firesoft-de <firestorm1331@live.de>, Author <author@noreply.github.com>
Betreff: Re: [so-fancy/diff-so-fancy] Enconding problems with color.diff.meta (#361)


There is also this config option<https://github.com/so-fancy/diff-so-fancy#useunicoderuler>.

**Comment by rdnlsmith** [comment]
This happened for me as well. I'm using:

* Windows Terminal 0.9.433.0
* PowerShell Core 6.2.4
* Git 2.25.1.windows.1

Setting `meta = yellow bold`, for instance, works fine, or even a different number like `52`. It seems to be specifically the `11` which produces the odd symbols.

**Comment by OJFord** [comment]
Do you see the same issue with `echo -e "\\033[38;5;11m foo"`?

**Comment by rdnlsmith** [comment]
I ran the PowerShell [equivalent](https://powershell.org/forums/topic/how-to-use-ansi-vt100-formatting-in-powershell-ooh-pretty-colors/) and got this:

![image](https://user-images.githubusercontent.com/4039042/75451922-59a4b680-593f-11ea-9065-4b03178fc79a.png)

I also ran it in Git Bash (still via Windows Terminal) and got this:

![image](https://user-images.githubusercontent.com/4039042/75451976-67f2d280-593f-11ea-9cc5-f5dbbaa0b221.png)

Possibly related, if I attempt to use a number to specify a highlight background color (_e.g._ `oldHighlight = red bold 52` as in the README), I get the same shade of grey no matter what:

![image](https://user-images.githubusercontent.com/4039042/75452586-91f8c480-5940-11ea-8d47-550a23d1644e.png)

This occurs in both PowerShell and Git Bash. I'm not certain whether it's a limitation of Windows Terminal, or if it's a Windows-specific problem in d-s-f. For now, I'm using _e.g._ `red bold reverse` instead, which does work:

![image](https://user-images.githubusercontent.com/4039042/75452712-c0769f80-5940-11ea-8bfd-ad9acb46e9d8.png)

**Comment by rdnlsmith** [comment]
I think this confirms that Windows Terminal is capable of displaying both foreground and background colors specified via ANSI escapes:

![image](https://user-images.githubusercontent.com/4039042/75453573-1ac43000-5942-11ea-83c1-c80a54579aa2.png)

**Comment by scottchiefbaker** [comment]
The Perl equivalent would be:

```
perl -E 'binmode(STDOUT, "encoding(UTF-8)"); $bar = "\x{2500}" x 50; $yellow = "\e[38;5;11m"; print "$yellow$bar\n";'
```

What output do you get from that? Whatever we come up with, this is going to end up being some weird terminal problem.

**Comment by rdnlsmith** [comment]
In Git Bash, I got the weird glyphs:

![image](https://user-images.githubusercontent.com/4039042/75486483-99d55a80-597a-11ea-94c8-77c65c8cc52c.png)

I tried to run it in PowerShell, and got an error. I'm sure I'm probably doing this wrong.

![image](https://user-images.githubusercontent.com/4039042/75486659-ed47a880-597a-11ea-9667-62019115ba1e.png)

**Comment by scottchiefbaker** [comment]
PowerShell may not understand the ' vs " (I'm not a PowerShell expert). 

Write those commands to a text file and then run perl.exe on that script.

**Comment by rdnlsmith** [comment]
That executed. I got the glyphs again.

![image](https://user-images.githubusercontent.com/4039042/75487423-61cf1700-597c-11ea-8392-3ff444747997.png)

**Comment by scottchiefbaker** [comment]
I'm at a loss... clearly diff-so-fancy is doing the right thing, it's just something with your terminal that's interpreting the UTF-8 characters incorrectly.

**Comment by rdnlsmith** [comment]
I'm not sure it's UTF-8, necessarily. If I use `\e[38;5;52m` instead of `\e[38;5;11m`, it draws the lines correctly, although the colors are still incorrect.

My thought was perhaps that the escape sequence with `11` is changing the code page? But, I don't if that's even possible. I also wonder if it could have something to do specifically with the `perl.exe` that ships with Git for Windows. I may just open an issue for Windows Terminal and see what they think.

Thanks for your effort!

![image](https://user-images.githubusercontent.com/4039042/75487934-5defc480-597d-11ea-958b-e49f790e218a.png)

**Comment by scottchiefbaker** [comment]
Definitely a weird issue. Let me know what you find.

**Comment by rdnlsmith** [comment]
It [seems like](https://github.com/microsoft/terminal/issues/4738#issuecomment-592213819) this issue is a limitation of perl-for-Windows. I had the thought to create a [PowerShell-based version](https://github.com/rdnlsmith/pwsh-diff), which works nicely&mdash;except, perhaps unsurprisingly, less-for-Windows has the same problem, and there doesn't seem to be a suitable Windows-native alternative (you can pipe it through `Out-Host -Paging`, but it only pages forwards).

**Comment by scottchiefbaker** [comment]
Does it work if you use cygwin / bash?

**Comment by rdnlsmith** [comment]
Cygwin exhibits the same problem. I imagine that WSL would work, on account of having native Linux binaries instead of (old-ish) Windows versions. I was just hoping to have a more "native" solution.

Anyways, it seems like this is solidly outside of d-s-f's control, so you may as well close the issue in my opinion. Perhaps you might mention in the README that Windows users without WSL might want to use

```diff
  git config --global color.diff-highlight.oldNormal    "red bold"
- git config --global color.diff-highlight.oldHighlight "red bold 52"
+ git config --global color.diff-highlight.oldHighlight "red bold reverse"
  git config --global color.diff-highlight.newNormal    "green bold"
- git config --global color.diff-highlight.newHighlight "green bold 22"
+ git config --global color.diff-highlight.newHighlight "green bold reverse"

- git config --global color.diff.meta       "11"
+ git config --global color.diff.meta       "yellow bold"
```

instead of the other settings. I also may yet continue my PowerShell effort, in hopes that a [better pager](https://github.com/PowerShell/PowerShell/issues/7851) might come along.

Thanks again for your time!

**Comment by scottchiefbaker** [comment]
Glad we sort of got things resolved.
