### ISSUE TITLE
possible to use with git commit -v?

### ISSUE THREAD

**Issue by zachvalenta** [so-fancy/diff-so-fancy#365]
Is it possible to configure `diff-so-fancy` to be used when committing with the `-v` (verbose) flag? I already use for `git diff` but the other primary time I'm looking at diffs is when I commit and it'd be great to use DSF then as well.

Keep up the good work, great tool.

**Comment by AlmightyYakob** [comment]
I had this exact same question, glad I'm not the only one

**Comment by scottchiefbaker** [comment]
I'm not familiar... can you provide your workflow for this?

**Comment by AlmightyYakob** [comment]
For better context when writing commit messages, I'll often use `git commit -v`, so that I can directly see the diff in the editor when writing the message. However, that uses the standard diffing system, which is a lot uglier than `diff-so-fancy`. Ideally, there'd be a way to use `diff-so-fancy` in this step as well, so that the diff we see in verbose mode is cleaner. However I realize there's probably limitations to this, as normally it runs in the shell, while this use case would be in the actual editor itself.

**Comment by scottchiefbaker** [comment]
I didn't even know `git commit -v` was a thing. That's neat!

Ultimately this is a git question? Git gets it's diff information for that mode from the command line somewhere and populates your `$EDITOR`. I would theorize it's possible, but I not a git expert.

Ultimately this is beyond the scope of d-s-f, as it's a git mode issue.

**Comment by OJFord** [comment]
@AlmightyYakob, d-s-f's way into git is as a pager, (or rather, as a pre-processing pass before your real pager, like `less`, but as far as git's concerned it's part of the pager) so it's only used with git commands that use (or can use) a pager.

That said, you could configure this, possibly in a number of ways but the first that comes to mind is as a [`prepare-commit-msg` hook](https://git-scm.com/docs/githooks#_prepare_commit_msg) that inserts your modified (by d-s-f) diff.

**Comment by jsjoeio** [comment]
Did you ever figure this out? @AlmightyYakob

**Comment by AlmightyYakob** [comment]
> Did you ever figure this out? @AlmightyYakob

No, I've just accepted the uglier git diff for now.
