### ISSUE TITLE
Any way to use this with tig?

### ISSUE THREAD

**Issue by hasufell** [so-fancy/diff-so-fancy#372]
https://github.com/jonas/tig

**Comment by OJFord** [comment]
No idea, see tig docs for whether it respects git config, and if not how to configure the pager.

**Comment by scottchiefbaker** [comment]
@hasufell d-s-f is just a wrapper around the `git diff` output. I assume tig uses something similar, but I don't know how to configure tig to shell out to d-s-f.

If you figure it out please let us know so we can update the docs.

**Comment by hasufell** [comment]
I've found https://github.com/jonas/tig/issues/542

**Comment by scottchiefbaker** [comment]
Wow that's way cool. Lots of love for d-s-f there :)

**Comment by OJFord** [comment]
Judging from that issue, it's not a matter of diff-so-fancy lacking support or doing something unexpected; just that `tig` doesn't respect git config for pagers, and supports by other means `diff-highlight` but not `diff-so-fancy`.

So, closing here, since it's a matter of tig support and that's better tracked there. Cheers.
