### ISSUE TITLE
Can I use it with vim-fugitive?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [so-fancy/diff-so-fancy#463]
I tried:

```
[pager]
	diff = diff-so-fancy | less --tabs=4 --RAW-CONTROL-CHARS --quit-if-one-screen
```
and got raw git diff, without colors :(

diff-so-fancy works for me in my shell, for `git diff`. I use Kitty on Gentoo. [My git config is here](https://gitlab.com/vitaly-zdanevich-configs/git/-/blob/ef05add4fbf27e6547406ec6b21d2c6537ced3a6/config).

See related issue https://github.com/tpope/vim-fugitive/issues/2132

**Comment by OJFord** [comment]
Works fine for me with:
```
$git config pager.diff
diff-so-fancy | less --tabs=4 -RFX
```

or as plain `diff-so-fancy`.

It also seems to work with your `less` args for me, though what I assume is the effect of `--RAW-CONTROL-CHARS` does not look like you screenshots in the linked issue (a Kitty thing?).

Anyway, closing, because it doesn't seem to be a diff-so-fancy issue, nor vim-fugitive. Try without the pipe to less, and with that works, experiment with those args.

**Comment by vitaly-zdanevich** [comment]
> diff-so-fancy | less --tabs=4 -RFX

Tried this: again raw diff with no colors :(

![image](https://user-images.githubusercontent.com/3514015/224480907-ff655a96-9b0b-4de1-ad2b-4dcf8cc32a1b.png)

**Comment by OJFord** [comment]
Well it works for me in all three configurations with:
```
alacritty 0.11.0 (8dbaa0bb)

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Feb 21 2023 18:10:20)
Included patches: 1-1337

fugitive @ b73a8e97de95d26280082abb7f51465a3d3b239e

dsf 1.4.3
```

it's something about your environment.

**Comment by rodhash** [comment]
> Works fine for me with:
> 
> ```
> $git config pager.diff
> diff-so-fancy | less --tabs=4 -RFX
> ```

This worked for me as well, thanks for the tip.
