### ISSUE TITLE
Trailing whitespace highlight broken

### ISSUE THREAD

**Issue by paulirish** [so-fancy/diff-so-fancy#85]
Here's a view of trailing space highlighting kinda breaking with diff-so-fancy:

![image](https://cloud.githubusercontent.com/assets/39191/13185591/e61a719c-d6f6-11e5-985d-4d5a1011c52b.png)

Original output:
```
[1;31m-    dir="$(cd -P "$( dirname "$src" )" && pwd)"[m
[1;32m+[m[1;32m    dir="$(cd -P "$( dirname "$src" )" && pwd)"[m[7;31m [m
     src="$(readlink "$src")"[m
[1;31m-    [[ $src != /* ]] && src="$dir/$src"[m
[1;32m+[m[1;32m    [[ $src != /* ]] && src="$dir/$src"[m[7;31m [m
```

**Comment by paulirish** [comment]
Closing as its my own bug report and I'm also not feeling up to fixing it. :)

**Comment by stevemao** [comment]
@paulirish Sorry, it looks right to me. What exactly is the problem? The lightgreen is highlighting the added whitespace?

**Comment by noscript** [comment]
I guess the trailing white spaces are expected to be highlight with red, when enabled.

**Comment by stevemao** [comment]
It's probably `diff-highlight`'s problem then.

**Comment by stevemao** [comment]
It is quite strange though... but a very minor problem.

**Comment by stevemao** [comment]
`git --no-pager diff --color | diff-highlight` confirmed it's a bug in diff-highlight

**Comment by paulirish** [comment]
Ah yes. this is diff-highlight's bug. :)

![image](https://cloud.githubusercontent.com/assets/39191/13317638/07b52e64-db6b-11e5-8929-de512f8cabca.png)

**Comment by stevemao** [comment]
Rather than a bug, it's just a bit inconsistent.. I didn't notice it so I guess most people won't :)

**Comment by stevemao** [comment]
@peff Are you aware of this? Also how can we contribute to `diff-highlight`?

**Comment by peff** [comment]
I'm not sure if this is a bug in diff-highlight, as much as it is inherently in conflict with the ANSI codes that the whitespace-highlighter is using. Here's a simple case:

```
$ echo foo >file
$ git add file && git commit -qm base
$ echo "foo " >file

$ git diff --color | tail -2 | cat -A
^[[31m-foo^[[m$
^[[32m+^[[m^[[32mfoo^[[m^[[41m ^[[m$

$ git diff --color | diff-highlight | tail -2 | cat -A
^[[31m-foo^[[m^[[7m^[[27m$
^[[32m+^[[m^[[32mfoo^[[m^[[41m^[[7m ^[[m^[[27m$
```

So the original turns off all colors (to shut off the green), then turns on code 41 (red background), shows the space, and then turns off colors.

`diff-highlight` sees that the difference is the extra space, and highlights it. So we again shut off all colors, then turn on the red, and _then_ we turn on our highlighting. I use the default config (shocker), which uses code 7, to invert foreground and background. So we would see red-on-white, but of course there's no text, so I just see a white background.

So really, the problem is just that both the whitespace-checker and diff-highlight want to colorize the same segment, and their colors are in conflict. `diff-highlight` shifts existing ANSI codes to the outside of the highlighted segment. It has to do this at the very least for any resets, since they would override our highlighting. But in this case, we also shift the "red background" outside, and it has no content. We could perhaps hack around that in this case by trying to retain colorization inside our segment, but I don't think it works in the general case. E.g., consider:

```
$ echo abc >file
$ git add file && git commit -qm base
$ echo "abcd " >file
```

where the whitespace-highlighted segment overlaps with the diff-highlighted segment. One is going to have to clobber the other Though in this instance, it doesn't look so bad; the highlight is clobbered, but there's no content after the whitespace. You might be able to come up with an example based on another whitespace problem (e.g., a tabs vs spaces one, which can appear in the middle of a line).

Your case is a little different, since you've configured the highlight codes. Using the config from the diff-so-fancy README, the same `cat -A` gives me:

```
^[[1;31m-foo^[[m^[[1;31;48;5;52m^[[m^[[1;31m^[[m$
^[[1;32m+foo^[[m^[[1;32;48;5;22m ^[[m^[[1;32m^[[m$
```

You've configured a "normal" color, so instead of set/reset, that takes over the whole line, erasing any other colors we got from git. I don't recall the details there on why it must clobber the whole line, though, and I don't see anything in what I posted to the mailing list.

So there may be some room for improvement there, but it's rather tricky. And best case you can run into the overlap problem I showed with the stock config.

> Also how can we contribute to diff-highlight?

Patches are welcome. Discussion and development happen on the git mailing list, so following SubmittingPatches in `git/git` would be the simplest thing from my perspective. There's an experimental-ish system to do pull requests against git/git and have them forwarded to the list (I think if you open a PR a bot will leave a comment with instructions).
